version: '3.8'
services:
  es-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es-node1
    environment:
      - node.name=es-node1
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es-node2,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-node1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  es-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es-node2
    environment:
      - node.name=es-node2
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es-node1,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-node2:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300

  es-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es-node3
    environment:
      - node.name=es-node3
      - cluster.name=my-es-cluster
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-node3:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
      - 9302:9300

volumes:
  esdata-node1:
    driver: local
  esdata-node2:
    driver: local
  esdata-node3:
    driver: local
